table _Measures
	lineageTag: 73a6f4a9-f80b-462b-9cbd-9d0bb8d7f207

	measure Title_Season_Race_Results = ```
			
			
			Var __Season = MAX( Dim_Races[Season] )
			
			Return
			
			__Season & " RACE RESULTS"
			
			```
		lineageTag: f8f06755-0169-4bf5-b23d-aac259aea3e4

	measure RaceResults_Total_Laps = MAX( Race_Results[Laps] )
		formatString: 0
		lineageTag: 46de2255-ad69-4fd2-aca2-0ebeccd9da05

	measure RaceResults_Total_Time = UDF_FormatSecs_HHMMSS( [TotalRaceTime_S] )
		lineageTag: 41160425-95b8-4844-8d8b-779784acd855

	measure TotalRaceTime_S = SUM( Race_Results[Race_Time_S] )
		lineageTag: be1d1415-2873-4a37-a1d6-4b60732be7eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column __
		dataType: string
		lineageTag: ee5a04e9-8e0e-44c5-8542-243477edf43c
		summarizeBy: none
		sourceColumn: __

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "__"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

